Implement EDD Newsletter tool
awesomemotive/edd-mailpoet pull request #35
Opened 2021-11-22 20:29 UTC by robincornett

2021-12-09 20:26 UTC, robincornett commented
Marking as ready for review (pending finalization of the newsletter tool). A little more manageable to test because of it being local.

Some notes:
- The ID is set to `wysija` because that's what the option names use...although it might be nice to update it, this makes more sense because I don't have to override things like the checkout label, list, etc.
- I set an early return in the `init` method to just not do anything if no MailPoet is detected at all, and removed the later `class_exists( 'WYSIJA' )` checks, because at that point it should be version 3 or the original.
- This `subscribe_email` method does currently return a boolean but I don't know that it's necessary. It might be nice to add some `edd_debug_log` calls to the Exceptions but I'd prefer to do that in a separate issue.

2021-12-10 13:53 UTC, ashleyfae commented on includes/class-edd-mailpoet.php
> +	 * @todo Should this be wysija instead? The existing settings, etc. all use that.
Is this `@todo` out of date with what's actually set?  It's set to `'wysija'` but you're asking if it should _"be wysija instead?"_

2021-12-10 13:54 UTC, ashleyfae commented on includes/class-edd-mailpoet.php
>   * @since       2.0
Should we add `@since 1.4.4 Refactored to use new base class.` ?

2021-12-10 14:04 UTC, robincornett commented on includes/class-edd-mailpoet.php
> +	 * @todo Should this be wysija instead? The existing settings, etc. all use that.
Yes, I had put that comment in last week or sometime in the past, and decided this week that the ID really should be `wysija`--which is different than what it is in the current release--I am thinking this is okay, though, since it's a total rewrite. I guess one holdup would be any permanently saved metadata which uses the ID would maybe look wrong since it would be using the old name, but I don't know that it's an issue in this particular extension.

2021-12-10 16:43 UTC, ashleyfae commented on includes/class-edd-mailpoet.php
> +	 * @todo Should this be wysija instead? The existing settings, etc. all use that.
Yeah, I think it should be set to whatever all/most of the current meta keys, settings, etc. uses. I assume that's `wysija`.

2021-12-10 16:46 UTC, ashleyfae commented
## Test List

- [ ] Selected default list remains the same between `master` and this branch.
- [ ] Individual download list remains the same between `master` and this branch.
- [ ] New user subscribed during checkout.
- [ ] New user not subscribed during checkout if box isn't checked.

2021-12-10 16:52 UTC, ashleyfae requested changes
> Individual download list remains the same between master and this branch.

This isn't working. I think master branch is using `mailpoet` for that meta key.

2021-12-10 17:26 UTC, robincornett commented
Sorry, yes, it does--fixed that and also had to update the newsletter tool class because the `checked()` function was not echoing.

2021-12-14 10:31 UTC, ashleyfae approved these changes

2021-12-14 10:32 UTC, merged